# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TebNoConfirmation.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import resources
from OSHandling import OSHandling 

class Ui_TebnoConfirmation(object):
    def setupUi(self, TebnoConfirmation):
        QtGui.QFontDatabase.addApplicationFont(':/fonts/Vazirmatn-Bold.ttf')
        self.font = QtGui.QFont()
        self.font.setFamily("Vazirmatn")
        self.font.setPointSize(10)
        TebnoConfirmation.setObjectName("TebnoConfirmation")
        TebnoConfirmation.resize(433, 304)
        TebnoConfirmation.setMinimumSize(QtCore.QSize(433, 304))
        TebnoConfirmation.setMaximumSize(QtCore.QSize(433, 304))
        #Style Path
        with open(OSHandling.styleHandling(), 'r') as f:
            TebnoConfirmation.setStyleSheet(f.read())
        self.widget = QtWidgets.QWidget(TebnoConfirmation)
        self.widget.setGeometry(QtCore.QRect(24, 20, 391, 251))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.name_lbl = QtWidgets.QLabel(self.widget)
        self.name_lbl.setObjectName("name_lbl")
        self.name_lbl.setFont(self.font)
        self.verticalLayout.addWidget(self.name_lbl)
        self.name = QtWidgets.QLineEdit(self.widget)
        self.name.setMaxLength(25)
        self.name.setObjectName("name")
        self.name.setFont(self.font)
        self.verticalLayout.addWidget(self.name)
        self.fname_lbl = QtWidgets.QLabel(self.widget)
        self.fname_lbl.setObjectName("fname_lbl")
        self.fname_lbl.setFont(self.font)
        self.verticalLayout.addWidget(self.fname_lbl)
        self.fname = QtWidgets.QLineEdit(self.widget)
        self.fname.setMaxLength(30)
        self.fname.setObjectName("fname")
        self.fname.setFont(self.font)
        self.verticalLayout.addWidget(self.fname)
        self.phone_lbl = QtWidgets.QLabel(self.widget)
        self.phone_lbl.setObjectName("phone_lbl")
        self.phone_lbl.setFont(self.font)
        self.verticalLayout.addWidget(self.phone_lbl)
        self.phoneNumber = QtWidgets.QLineEdit(self.widget)
        self.phoneNumber.setMaxLength(15)
        self.phoneNumber.setObjectName("phoneNumber")
        self.verticalLayout.addWidget(self.phoneNumber)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.submitBtnConfirm = QtWidgets.QPushButton(self.widget)
        self.submitBtnConfirm.setObjectName("submitBtnConfirm")
        self.verticalLayout.addWidget(self.submitBtnConfirm)

        self.retranslateUi(TebnoConfirmation)
        QtCore.QMetaObject.connectSlotsByName(TebnoConfirmation)

    def retranslateUi(self, TebnoConfirmation):
        _translate = QtCore.QCoreApplication.translate
        TebnoConfirmation.setWindowTitle(_translate("TebnoConfirmation", "Form"))
        self.name_lbl.setText(_translate("TebnoConfirmation", "نام:"))
        self.fname_lbl.setText(_translate("TebnoConfirmation", "نام خانوادگی:"))
        self.phone_lbl.setText(_translate("TebnoConfirmation", "شماره همراه:"))
        self.submitBtnConfirm.setText(_translate("TebnoConfirmation", "ثبت اطلاعات"))



