# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TebNoWarning.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import resources
from OSHandling import OSHandling

class Ui_TebNoProduct(object):
    def setupUi(self, TebNoProduct):
        QtGui.QFontDatabase.addApplicationFont(':/fonts/Vazirmatn-Bold.ttf')
        self.font = QtGui.QFont()
        self.font.setFamily("Vazirmatn")
        self.font.setPointSize(12)
        TebNoProduct.setObjectName("TebNoProduct")
        TebNoProduct.resize(389, 532)
        #Style Path
        with open(OSHandling.styleHandling(), 'r') as f:
            TebNoProduct.setStyleSheet(f.read())
        TebNoProduct.setMinimumSize(QtCore.QSize(389, 532))
        TebNoProduct.setMaximumSize(QtCore.QSize(389, 532))
        self.tebno_lbl = QtWidgets.QLabel(TebNoProduct)
        self.tebno_lbl.setGeometry(QtCore.QRect(100, 30, 191, 151))
        self.tebno_lbl.setText("")
        self.tebno_lbl.setPixmap(QtGui.QPixmap(":/images/TebNoLogo.png"))
        self.tebno_lbl.setObjectName("tebno_lbl")
        self.TebnoWarning = QtWidgets.QTextEdit(TebNoProduct)
        self.TebnoWarning.setGeometry(QtCore.QRect(20, 190, 351, 331))
        self.TebnoWarning.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.TebnoWarning.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.TebnoWarning.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.TebnoWarning.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.TebnoWarning.setReadOnly(True)
        self.TebnoWarning.setFont(self.font)
        self.TebnoWarning.setAlignment(QtCore.Qt.AlignCenter)
        self.TebnoWarning.setObjectName("TebnoWarning")

        self.retranslateUi(TebNoProduct)
        QtCore.QMetaObject.connectSlotsByName(TebNoProduct)

    def retranslateUi(self, TebNoProduct):
        _translate = QtCore.QCoreApplication.translate
        TebNoProduct.setWindowTitle(_translate("TebNoProduct", "Form"))
        self.TebnoWarning.setPlainText(_translate("TebNoProduct", \
            "طبنو، توسط آرگونز طراحی شده است. هرگونه کپی برداری یا استفاده از نسخه رایگان غیر قانونی، پیگرد قانونی دارد. \n سایت ما: \n https://argonz.ir"))




