# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VisitDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import resources
import os
from OSHandling import OSHandling



class Ui_visitDialog(object):
    def setupUi(self, visitDialog):
        QtGui.QFontDatabase.addApplicationFont(':/fonts/Vazirmatn-Bold.ttf')
        self.font = QtGui.QFont()
        self.font.setFamily("Vazirmatn")
        self.font.setPointSize(10)
        visitDialog.setObjectName("visitDialog")
        visitDialog.resize(300, 500)
        visitDialog.setMinimumSize(QtCore.QSize(300,500))
        visitDialog.setMaximumSize(QtCore.QSize(300,500))
        #Style Path
        with open(OSHandling.styleHandling(), 'r') as f:
            visitDialog.setStyleSheet(f.read())
        self.verticalLayout = QtWidgets.QVBoxLayout(visitDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.visitStatusLbl = QtWidgets.QLabel(visitDialog)
        self.visitStatusLbl.setObjectName("visitStatusLbl")
        self.visitStatusLbl.setFont(self.font)
        self.verticalLayout.addWidget(self.visitStatusLbl)
        self.visitStatus = QtWidgets.QComboBox(visitDialog)
        self.visitStatus.setObjectName("visitStatus")
        self.visitStatus.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.visitStatus.setFont(self.font)
        self.verticalLayout.addWidget(self.visitStatus)
        self.visitHourLbl = QtWidgets.QLabel(visitDialog)
        self.visitHourLbl.setObjectName("visitHourLbl")
        self.visitHourLbl.setFont(self.font)
        self.verticalLayout.addWidget(self.visitHourLbl)
        self.visitHour = QtWidgets.QLineEdit(visitDialog)
        self.visitHour.setAlignment(QtCore.Qt.AlignCenter)
        self.visitHour.setObjectName("visitHour")
        self.verticalLayout.addWidget(self.visitHour)
        self.visitDateLbl = QtWidgets.QLabel(visitDialog)
        self.visitDateLbl.setObjectName("visitDateLbl")
        self.visitDateLbl.setFont(self.font)
        self.verticalLayout.addWidget(self.visitDateLbl)
        self.visitDate = QtWidgets.QLineEdit(visitDialog)
        self.visitDate.setObjectName("visitDate")
        self.verticalLayout.addWidget(self.visitDate)
        self.visitDescriptionLbl = QtWidgets.QLabel(visitDialog)
        self.visitDescriptionLbl.setObjectName("visitDescriptionLbl")
        self.visitDescriptionLbl.setFont(self.font)
        self.verticalLayout.addWidget(self.visitDescriptionLbl)
        self.visitDescription = QtWidgets.QTextEdit(visitDialog)
        self.visitDescription.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.visitDescription.setObjectName("visitDescription")
        self.visitDescription.setFont(self.font)
        self.verticalLayout.addWidget(self.visitDescription)
        self.visitEditBtn = QtWidgets.QPushButton(visitDialog)
        self.visitEditBtn.setObjectName("visitEditBtn")
        self.visitEditBtn.setFont(self.font)
        self.verticalLayout.addWidget(self.visitEditBtn)

        self.retranslateUi(visitDialog)
        QtCore.QMetaObject.connectSlotsByName(visitDialog)

    def retranslateUi(self, visitDialog):
        _translate = QtCore.QCoreApplication.translate
        visitDialog.setWindowTitle(_translate("visitDialog", "Dialog"))
        self.visitStatusLbl.setText(_translate("visitDialog", "وضعیت نوبت:"))
        self.visitHourLbl.setText(_translate("visitDialog", "ساعت نوبت:"))
        self.visitHour.setInputMask(_translate("visitDialog", "99:99"))
        self.visitDateLbl.setText(_translate("visitDialog", "تاریخ نوبت:"))
        self.visitDate.setInputMask(_translate("visitDialog", "1999/99/99"))
        self.visitDescriptionLbl.setText(_translate("visitDialog", "توضیحات:"))
        self.visitEditBtn.setText(_translate("visitDialog", "ویرایش نوبت"))


